# theme = "acme"
# theme = "ayu_dark"
# theme = "ayu_mirage"
# theme = "bogster_light"
# theme = "everforest_light"
# theme = "gruvbox"
# theme = "gruvbox_light"
# theme = "kanagawa"
# theme = "molokai"
# theme = "papercolor-light"
# theme = "solarized_light"
# theme = "solarized_dark"
theme = "sonokai"


[editor]
cursorline = true
bufferline = "always"
color-modes = true
idle-timeout = 0

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
# left = ["mode", "diagnostics"]
center = ["file-name", "file-modification-indicator", "spinner"]
# right = ["version-control", "spacer", "spacer", "separator", "selections", "file-type", "file-encoding", "position-percentage", "position"]
left = ["mode", "spacer", "diagnostics", "spacer", "version-control"]
right = ["selections", "file-type", "file-encoding", "position-percentage", "position"]

[editor.indent-guides]
render = false

[editor.lsp]
display-messages = true
display-signature-help-docs = false

# [keys.insert]
# C-p = "signature_help"