theme = "kanagawa"

[editor]
cursorline = true
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "diagnostics"]
center = ["file-name", "file-modification-indicator", "spinner"]
right = ["version-control", "spacer", "spacer", "separator", "selections", "file-type", "file-encoding", "position-percentage", "position"]

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true
display-signature-help-docs = false

# [keys.insert]
# C-p = "signature_help"