[[language]]
name = "python"
# rulers = [89] 
roots = ["pyproject.toml"]
auto-format = false
formatter = { command = "black", args = ["--quiet", "-"] }
# language-server = { command = "pyright-langserver", args = ["--stdio"] }
# config = {} # <- this is the important line