language en_US
set guifont=Cartograph\ CF:h10
set number
set hidden
set linebreak
set clipboard^=unnamed
command Root cd %:p:h:h
command File cd %:p:h
syntax on

set visualbell
set vb t_vb=

tnoremap <Esc> <C-\><C-n>
:nnoremap <C-n> :bnext<CR>
:nnoremap <C-p> :bprevious<CR>
:imap <C-w> <C-o><C-w>
:map <C-Tab> <C-W>w

" colorscheme onedark
" colorscheme Papercolor
" set background=light

" set autochdir
autocmd BufEnter * silent! lcd %:p:h

command! Bd bp|bd #

let g:slime_target = "tmux"
let g:slime_default_config = {"socket_name": "default", "target_pane": "{last}"}
